# Site settings
author: Olivia
title: Olivia Codes
header-img: img/home-bg.png
email: olivia.joy.hanson@gmail.com
copyright_name: Olivia
description: > # this means to ignore newlines until "baseurl:"
  The coding struggle is real, so let's try this out together.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  OliviaJoyHanson

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
